### ISSUE TITLE
Hello, how to download data?

### ISSUE THREAD

**Issue by lanfeiwuwudibang** [sgraine/HIL-coral-segmentation#1]
I have read your project and I think it is very interesting. I want to learn it, but I cannot download the data. Can you provide the download link of the data?

**Comment by sgraine** [comment]
Hi ! Unfortunately, as we did not create the dataset used in this work we cannot provide access to it. Please reach out to the authors of the original works for access: https://sites.google.com/a/unizar.es/semanticseg/home.
